
platform :ios, '9.0'

target 'SCSegmentControl_Example' do
  pod 'SCSegmentControl', :path => '../'
  pod 'Masonry', '~> 1.1.0'

  target 'SCSegmentControl_Tests' do
    inherit! :search_paths

    
  end
end
